<?php

namespace App\Services;

use App\Jobs\RefreshVisitorCounts;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

/**
 * Pre-aggregated dashboard figures.
 *
 * The source polled a static live_orders.json every 2 seconds, regenerated by
 * a cron script. Pre-aggregating was the right instinct at this volume — this
 * keeps it but makes staleness visible: every payload carries the time it was
 * computed, so a stalled cache reads as stale rather than as a dead store.
 */
class DashboardMetrics
{
    public const CACHE_KEY = 'admin:dashboard:metrics';

    /** 30s, not the source's 2s: these figures move a few times an hour. */
    public const CACHE_TTL = 30;

    /** Statuses that count as revenue — cancelled and failed orders do not. */
    private const EARNING = [
        Order::STATUS_NEW,
        Order::STATUS_PROCESSING,
        Order::STATUS_IN_DELIVERY,
        Order::STATUS_COMPLETED,
    ];

    /** @return array<string, mixed> */
    public function all(): array
    {
        return Cache::remember(self::CACHE_KEY, self::CACHE_TTL, function () {
            $today = Carbon::today();
            $monthStart = Carbon::now()->startOfMonth();
            $lastMonthStart = (clone $monthStart)->subMonth();

            return [
                'generated_at' => now()->toIso8601String(),
                'today' => [
                    'sales' => $this->salesBetween($today, Carbon::now()),
                    'orders' => $this->ordersBetween($today, Carbon::now()),
                ],
                'this_month' => ['sales' => $this->salesBetween($monthStart, Carbon::now())],
                'last_month' => ['sales' => $this->salesBetween($lastMonthStart, (clone $monthStart)->subSecond())],
                'all_time' => [
                    'sales' => $this->salesBetween(null, null),
                    'orders' => (int) Order::query()->whereIn('status', self::EARNING)->count(),
                    'returned' => (int) Order::query()->where('status', Order::STATUS_RETURNED)->count(),
                    'products' => (int) Product::query()->count(),
                ],
                'queues' => $this->queueCounts(),
                'trend' => $this->trend(),
            ];
        });
    }

    /**
     * The figures that move minute to minute. Kept out of all() so the live
     * feed can refresh them without recomputing the month-to-date aggregates.
     *
     * @return array<string, mixed>
     */
    public function live(): array
    {
        $today = Carbon::today();

        return [
            'generated_at' => now()->toIso8601String(),
            'visitors' => RefreshVisitorCounts::counts(),
            'today' => [
                'sales' => $this->salesBetween($today, Carbon::now()),
                'orders' => $this->ordersBetween($today, Carbon::now()),
            ],
            'queues' => $this->queueCounts(),
        ];
    }

    public function flush(): void
    {
        Cache::forget(self::CACHE_KEY);
    }

    private function salesBetween(?Carbon $from, ?Carbon $to): float
    {
        return (float) Order::query()
            ->whereIn('status', self::EARNING)
            ->when($from, fn ($q) => $q->where('created_at', '>=', $from))
            ->when($to, fn ($q) => $q->where('created_at', '<=', $to))
            ->sum('myr_value_include_postage');
    }

    private function ordersBetween(Carbon $from, Carbon $to): int
    {
        return (int) Order::query()
            ->whereIn('status', self::EARNING)
            ->whereBetween('created_at', [$from, $to])
            ->count();
    }

    /** @return array<int, int> */
    private function queueCounts(): array
    {
        return Order::query()
            ->groupBy('status')
            ->pluck(DB::raw('COUNT(*)'), 'status')
            ->map(fn ($n) => (int) $n)
            ->all();
    }

    /** Daily revenue for the last 14 days, zero-filled so gaps are visible. */
    private function trend(): array
    {
        $start = Carbon::today()->subDays(13);

        $rows = Order::query()
            ->whereIn('status', self::EARNING)
            ->where('created_at', '>=', $start)
            ->groupBy('day')
            ->pluck(
                DB::raw('SUM(myr_value_include_postage)'),
                DB::raw('DATE(created_at) as day'),
            );

        $series = [];

        for ($day = clone $start; $day <= Carbon::today(); $day->addDay()) {
            $key = $day->toDateString();
            $series[] = [
                'date' => $key,
                'label' => $day->format('j M'),
                'sales' => round((float) ($rows[$key] ?? 0), 2),
            ];
        }

        return $series;
    }
}
